<?php

namespace SkiSmileAdminBundle\Repository;

/**
 * FotoGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
