<?php

namespace SkiSmileAdminBundle\Repository;

/**
 * SkiRentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkiRentRepository extends \Doctrine\ORM\EntityRepository
{
}
