<?php

namespace SkiSmileAdminBundle\Repository;

/**
 * SkiServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkiServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
